name: ci

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"
      CGO_CFLAGS: "-O -D__BLST_PORTABLE__"
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        run: make test

  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"
      CGO_CFLAGS: "-O -D__BLST_PORTABLE__"
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install gofumpt
        run:  go install mvdan.cc/gofumpt@v0.4.0

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.2

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2

      - name: Lint
        run: make lint

      - name: Ensure go mod tidy runs without changes
        run: |
          go mod tidy
          git diff-index HEAD
          git diff-index --quiet HEAD
